version: "4.0"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_my2home
    restart: always
    environment:
      POSTGRES_DB: db_my2home
      POSTGRES_USER: user_my2home
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"